// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4_YpFNyX1p5KyWvkQgUvoXpYlcibBpUU',
    appId: '1:937341298462:web:debb9e71568951419b0b0f',
    messagingSenderId: '937341298462',
    projectId: 'helpy-moto-62e23',
    authDomain: 'helpy-moto-62e23.firebaseapp.com',
    storageBucket: 'helpy-moto-62e23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqMyqH-HOqVkcjZzHroDlFUsI_82gHsz0',
    appId: '1:937341298462:android:49c05e650ed4c4d59b0b0f',
    messagingSenderId: '937341298462',
    projectId: 'helpy-moto-62e23',
    storageBucket: 'helpy-moto-62e23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO_2Gf6Ho65IaArtA_09Os_Koaox-o734',
    appId: '1:937341298462:ios:14706a581c10f3229b0b0f',
    messagingSenderId: '937341298462',
    projectId: 'helpy-moto-62e23',
    storageBucket: 'helpy-moto-62e23.appspot.com',
    iosClientId: '937341298462-qomdv23icdhnhscq91c3tgban73jpsp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO_2Gf6Ho65IaArtA_09Os_Koaox-o734',
    appId: '1:937341298462:ios:14706a581c10f3229b0b0f',
    messagingSenderId: '937341298462',
    projectId: 'helpy-moto-62e23',
    storageBucket: 'helpy-moto-62e23.appspot.com',
    iosClientId: '937341298462-qomdv23icdhnhscq91c3tgban73jpsp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );
}
